sonar.projectKey=tusharkhoche_focused-research-agent
sonar.organization=sonarpythonautomation

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml